### PR TITLE
UIPOLICIES-14: Move reusable Authorization Policies to `stripes-authorization-components` repository

### PR DESCRIPTION
**Pull request by alisher-epam**
## Purpose

[https://folio-org.atlassian.net/browse/UIPOLICIES-14](https://folio-org.atlassian.net/browse/UIPOLICIES-14)

We have also supporting PR her [https://github.com/folio-org/ui-consortia-settings/pull/137](https://github.com/folio-org/ui-consortia-settings/pull/137)

## Approach

Consortium managers need to manage system policies at a high level, they need the ability to efficiently manage the creating and updating of policies for and on behalf of members of the system. As we discussed with our team the reusable components should be moved `stripes-authorization-components` and imported from the repo [stripes-authorization-components](https://github.com/folio-org/stripes-authorization-components/pull/20)

## Screenshots

https://github.com/user-attachments/assets/cb86bccf-6c7e-4cbe-946e-101982ab3e9b

## Pre-Merge Checklist
Before merging this PR, please go through the following list and take appropriate actions.
- [x] I've added appropriate record to the CHANGELOG.md
- Does this PR meet or exceed the expected quality standards?
  - [ ] Code coverage on new code is 80% or greater
  - [ ] Duplications on new code is 3% or less
  - [ ] There are no major code smells or security issues
- Does this introduce breaking changes?
  - [ ] If any API-related changes - okapi interfaces and permissions are reviewed/changed correspondingly
  - [ ] There are no breaking changes in this PR.

If there are breaking changes, please **STOP** and consider the following:

- What other modules will these changes impact?
- Do JIRAs exist to update the impacted modules?
  - [ ] If not, please create them
  - [ ] Do they contain the appropriate level of detail?  Which endpoints/schemas changed, etc.
  - [ ] Do they have all they appropriate links to blocked/related issues?
- Are the JIRAs under active development?
  - [ ] If not, contact the project's PO and make sure they're aware of the urgency.
- Do PRs exist for these changes?
  - [ ] If so, have they been approved?

Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies increase.

While it's helpful for reviewers to help identify potential problems, ensuring that it's safe to merge is ultimately the responsibility of the PR assignee.

### CODE REVIEW

**Comment by usavkov-epam** [comment]
Could you please explain why the changes are being made in the `ui-authorization-policies` module, not in `ui-consortia-settings`, if the **consortium manager** requires the support of cross-tenant auth policies?

**Comment by alisher-epam** [comment]
> Could you please explain why the changes are being made in the `ui-authorization-policies` module, not in `ui-consortia-settings`, if the **consortium manager** requires the support of cross-tenant auth policies?

Sorry to forget to mention. Here is the supporting PR, I have just created https://github.com/folio-org/ui-consortia-settings/pull/137

**Comment by usavkov-epam** [comment]
> > Could you please explain why the changes are being made in the `ui-authorization-policies` module, not in `ui-consortia-settings`, if the **consortium manager** requires the support of cross-tenant auth policies?
> 
> Sorry to forget to mention. Here is the supporting PR, I have just created [folio-org/ui-consortia-settings#137](https://github.com/folio-org/ui-consortia-settings/pull/137)

I'm afraid it won't work:
- https://folio-project.slack.com/archives/CAN13SWBF/p1687179380489659
- https://github.com/folio-org/ui-consortia-settings/pull/137#pullrequestreview-2237854714

**Comment by alisher-epam** [comment]
@usavkov-epam updated

**Comment by alisher-epam** [comment]
As we discussed with our team the reusable components should be moved `stripes-authorization-components` and imported from the repo [stripes-authorization-components](https://github.com/folio-org/stripes-authorization-components/pull/20)

**Review by artem-blazhko — APPROVED** [review]

**Comment by aidynoJ** [comment]
LGTM

**Review by aidynoJ — APPROVED** [review]

**Review by UladzislauKutarkin — APPROVED** [review]

**Pull request merged**
